name: Create & Upload kivy-ios prebuilt toolchain

on:
  workflow_dispatch:              # 手动触发
  schedule:
    - cron: '0 0 1 * *'           # 每月 1 号 00:00 UTC 自动跑一次，保持更新

jobs:
  build-toolchain:
    runs-on: macos-14             # 与正式打包 job 保持一致
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          brew install --quiet autoconf automake libtool pkg-config
          pip install buildozer kivy-ios cython packaging plyer

      - name: Build kivy-ios toolchain
        run: |
          # 让 buildozer 把 toolchain 下到 ~/.buildozer/ios/platform/kivy-ios
          buildozer ios update || true   # 第一次会编译

      - name: Pack toolchain
        run: |
          cd ~/.buildozer/ios/platform
          tar -czf kivy-ios.tar.gz kivy-ios

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ios-toolchain
          name: "kivy-ios prebuilt toolchain"
          files: ~/.buildozer/ios/platform/kivy-ios.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}