name: Build iOS IPA (unsigned, fast)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  ios:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Cache brew
        uses: actions/cache@v4
        with:
          path: |
            /usr/local/Homebrew
            ~/Library/Caches/Homebrew
          key: brew-${{ runner.os }}-${{ hashFiles('.github/workflows/ios.yml') }}

      - name: Install system dependencies
        run: |
          brew install --quiet autoconf automake libtool pkg-config
          pip install buildozer cython packaging plyer   # 不再装 kivy-ios

      - name: Download prebuilt kivy-ios
        run: |
          mkdir -p ~/.buildozer/ios/platform
          curl -L https://github.com/${{ github.repository }}/releases/download/ios-toolchain/kivy-ios.tar.gz \
            | tar -xz -C ~/.buildozer/ios/platform

    #   - name: Create Xcode project
    #     run: buildozer ios update

      - name: Build iOS package
        run: buildozer ios debug --no-debug

      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: GridRemover-unsigned
          path: bin/*.ipa