name: Build iOS IPA (unsigned)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install buildozer & kivy-ios
        run: |
          pip install --upgrade pip
          pip install buildozer kivy-ios

      - name: Build iOS package
        run: |
          buildozer ios debug

      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: GridRemover-unsigned
          path: bin/*.ipa